# Generated by Django 5.0.7 on 2024-12-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='details',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
