# Generated by Django 5.1.4 on 2025-01-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandName', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='uploads')),
                ('price', models.TextField()),
            ],
        ),
    ]
