# Generated by Django 5.1.4 on 2025-01-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carlist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
