# Generated by Django 5.1.4 on 2025-01-09 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_brand', '0001_initial'),
        ('car_list', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='carlist',
            old_name='brandName',
            new_name='CarName',
        ),
        migrations.RemoveField(
            model_name='carlist',
            name='Brand',
        ),
        migrations.AlterField(
            model_name='carlist',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carlist',
            name='Brand',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='car_brand.brand'),
        ),
    ]
