# Generated by Django 5.1.4 on 2025-01-09 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_brand', '0001_initial'),
        ('car_list', '0002_rename_brandname_carlist_carname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carlist',
            name='Brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_brand.brand'),
        ),
    ]
