# Generated by Django 5.1.4 on 2025-01-10 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_list', '0003_alter_carlist_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlist',
            name='quantity',
            field=models.IntegerField(default=None),
        ),
    ]
