# Generated by Django 5.1.4 on 2025-01-07 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_brand', '0001_initial'),
        ('car_list', '0004_alter_carlist_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carlist',
            name='author',
        ),
        migrations.AddField(
            model_name='carlist',
            name='Brand',
            field=models.ManyToManyField(to='car_brand.brand'),
        ),
    ]
