# Generated by Django 5.1.4 on 2025-01-07 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_brand', '0001_initial'),
        ('car_list', '0005_remove_carlist_author_carlist_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carlist',
            name='Brand',
            field=models.ManyToManyField(default=None, to='car_brand.brand'),
        ),
    ]
