# Generated by Django 5.1.4 on 2025-01-07 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_list', '0006_alter_carlist_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carlist',
            name='Brand',
        ),
    ]
