# Generated by Django 5.1.4 on 2024-12-31 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskTitle', models.CharField(max_length=50)),
                ('taskDescription', models.TextField()),
                ('is_Completed', models.BooleanField(default=False)),
                ('taskAssignDate', models.DateField()),
                ('cate', models.ManyToManyField(to='category.taskcategory')),
            ],
        ),
    ]
