# Generated by Django 4.1.9 on 2024-12-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='field',
            field=models.TextField(default='rahim'),
        ),
    ]
